name: Bug Report
description: Report a bug to help improve the modpack
labels: "auto: bug"
body:
- type: markdown
  attributes:
    value: "## Thank you for reporting a bug!"

- type: checkboxes
  id: exists
  attributes:
    label: Was this bug reported before?
    description: You can check using the search bar.
    options:
      - label: "No, it was not."
        required: true

- type: input
  id: log
  attributes:
    label: Please provide a link to your crash report or latest.log, if relevant
    description: "The `latest.log` file is found in `\/logs\/` within the modpack files.\nWe recommend always using https://mclo.gs/." 
    placeholder: https://mclo.gs/MydIQBu...

- type: input
  id: additional-mods
  attributes:
    label: If you have any, please provide a list of additional mods
    description: Leave blank if you have none.
    placeholder: OptiFine, Edible Crayons...

- type: textarea
  id: issue-description
  validations:
    required: true
  attributes:
    label: Please describe the issue you are experiencing
    description: Try to include detailed reproduction steps for the issue.
    placeholder: |
      Mo' Creatures pets are being glitchy.
      
      How to reproduce:
      1. Tame a Mo' Creatures pet on a server.
      2. Try to lead it somewhere with a lead.
      3. Discover that the pet will not obey to you despite your best efforts.
      4. Give up in shame and follow where the pet leads *you*.

- type: markdown
  attributes:
    value: |
      ---
      <a href="https://www.technicpack.net/modpack/tekkit-smp"><img src="https://i.imgur.com/H1c8pO5.png" width="64"></a>
